# Generated by Django 4.0.5 on 2022-06-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Russian', 'Russian')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
