# Generated by Django 4.0.4 on 2022-05-29 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Passed', 'Passed'), ('Missed', 'Missed')], default='Active', max_length=64),
        ),
        migrations.AlterField(
            model_name='talon',
            name='arriveTime',
            field=models.TimeField(default=datetime.time(0, 0), unique=True),
        ),
    ]
